- name: Homelab
  hosts: gokul
  roles:
      - common
      - role: docker
        become: true
        vars:
            ansible_user: gokul
      - role: jellyfin
        become: true
        vars:
            jellyfin_path: /tank/media/jellyfin
      - role: immich
        become: true
        vars:
            ansible_user: gokul
            immich_path: /tank/immich
      - role: navidrome
        become: true
        vars:
            navidrome_path: /tank/media/navidrome
