# SPDX-License-Identifier: MIT-0
---
# tasks file for roles/common

- name: Update package cache
  when: ansible_os_family == "Debian"
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    name:
      - python3-pip
      - python3-venv
      - git
      - nano
      - curl
      - wget
      - ca-certificates
      - gnupg
      - samba
      - smbclient
    state: present

- name: Setup samba
  ansible.builtin.template:
    src: samba.conf.j2
    dest: /etc/samba/smb.conf
    mode: '0644'

- name: Add samba user
  ansible.builtin.user:
    name: '{{ sudo_user }}'
    state: present
    create_home: true

- name: Add user to Samba database
  ansible.builtin.shell: >
    set -o pipefail;
    (echo "{{ common_samba_password }}"; echo "{{ common_samba_password }}") | smbpasswd -s -a {{ sudo_user }}
  register: common_smb_user_result
  changed_when: "'Added user' in common_smb_user_result.stdout"


- name: Copy borg pass
  ansible.builtin.copy:
    src: .borg.pass
    dest: "/opt/.borg.pass"
    mode: '0400'

- name: Copy application data backup script
  ansible.builtin.template:
    src: debian_backup_script.sh.j2
    dest: /usr/local/bin/debian-backup.sh
    mode: '0644'

- name: Setup application data backup cron
  ansible.builtin.cron:
    name: Take application data backup to oracle cloud
    hour: '18'
    minute: '00'
    user: root
    job: "/bin/bash /usr/local/bin/debian-backup.sh >> /var/log/debian-backup.log 2>&1"

- name: Copy zpool backup script
  ansible.builtin.template:
    src: zpool_backup.sh.j2
    dest: /usr/local/bin/zpool_backup.sh
    mode: '0644'

- name: Setup zpool data backup cron
  ansible.builtin.cron:
    name: Take zpool backup to oracle cloud
    hour: '19'
    minute: '00'
    user: root
    job: "/bin/bash /usr/local/bin/zpool_backup.sh >> /var/log/zpool-backup.log 2>&1"

- name: Setup cron for zpool scrub
  ansible.builtin.cron:
    name: zpool scrub
    minute: '00'
    hour: '10'
    day: '1'
    user: root
    job: "/usr/bin/zpool scrub tank"
