# SPDX-License-Identifier: MIT-0
---
# tasks file for roles/immich

- name: Create immich directory
  ansible.builtin.file:
    path: /opt/immich
    state: directory
    mode: '0755'

- name: Fetch docker-compose yml
  ansible.builtin.uri:
    url: https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
    dest: /opt/immich/docker-compose.yml
    mode: 600
    status_code: [200, 304]

- name: Copy immich .env file
  ansible.builtin.template:
    src: .env.j2
    dest: /opt/immich/.env
    mode: '400'


- name: Deploy immich container
  community.docker.docker_compose_v2:
    project_src: /opt/immich
    state: present
