services:
  homelab-exporter:
    image: gokul1630/homelab-exporter:latest
    # build: .
    container_name: homelab-exporter
    restart: unless-stopped
    pid: host
    ipc: host
    privileged: true
    volumes:
      - /:/host:ro
    ports:
      - "9877:9877"
    env_file:
      - .env
    networks:
      - immich_default
      - navidrome_default

networks:
  immich_default:
    external: true
  navidrome_default:
    external: true 
