services:
  homelab-exporter:
    build: .
    container_name: homelab-exporter
    restart: unless-stopped
    ports:
      - "9877:9877"
    env_file:
      - .env
    networks:
      - docmost_default
      - immich_default
      - navidrome_default

networks:
  docmost_default:
    external: true
  immich_default:
    external: true
  navidrome_default:
    external: true 
