# SPDX-License-Identifier: MIT-0
---
# tasks file for roles/jellyfin


- name: Create jellyfin directory
  ansible.builtin.file:
    path: /opt/jellyfin
    state: directory
    mode: '0700'
    owner: '1000'
    group: '1000'

- name: Deploy docker-compose template
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /opt/jellyfin/docker-compose.yml
    mode: '0400'
    owner: '1000'
    group: '1000'

- name: Deploy Jellyfin containers
  community.docker.docker_compose_v2:
    project_src: /opt/jellyfin
    state: present
