apiVersion: 1
groups:
    - orgId: 1
      name: eval-group
      folder: Disk alerts
      interval: 1m
      rules:
        - uid: efp0tejxn2b5sd
          title: zpool down
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: ffp0p4dk3d8n4c
              model:
                editorMode: builder
                expr: zpool_vdev_state{vdev="tank"}
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              queryType: expression
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: eq
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: adqlnrk
          panelId: 11
          noDataState: NoData
          execErrState: Error
          keepFiringFor: 1m
          annotations:
            __dashboardUid__: adqlnrk
            __panelId__: "11"
            summary: Zpool down
          labels: {}
          isPaused: false
          notification_settings:
            receiver: gokul
