# SPDX-License-Identifier: MIT-0
---
# tasks file for roles/common

- name: Update package cache
  become: true
  when: ansible_os_family == "Debian"
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    name:
      - python3-pip
      - python3-venv
      - git
      - nano
      - curl
      - wget
      - ca-certificates
      - gnupg
    state: present
