# SPDX-License-Identifier: MIT-0
---
# handlers file for roles/common
- name: Ensure Samba services are running
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
    enabled: true
  loop:
    - smbd
    - nmbd
